// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyxr2U0Y5H91A0FiPgW_MtEbZpPdRJgo',
    appId: '1:941297246376:ios:f00def0d49e0e7db64629d',
    messagingSenderId: '941297246376',
    projectId: 'mini-app-9f9aa',
    storageBucket: 'mini-app-9f9aa.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyxr2U0Y5H91A0FiPgW_MtEbZpPdRJgo',
    appId: '1:941297246376:ios:f00def0d49e0e7db64629d',
    messagingSenderId: '941297246376',
    projectId: 'mini-app-9f9aa',
    storageBucket: 'mini-app-9f9aa.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANvdwG5K7nOimHjoAvQ9Aqtmjc24dSu1M',
    appId: '1:941297246376:web:4cf85be0eb92951964629d',
    messagingSenderId: '941297246376',
    projectId: 'mini-app-9f9aa',
    authDomain: 'mini-app-9f9aa.firebaseapp.com',
    storageBucket: 'mini-app-9f9aa.firebasestorage.app',
    measurementId: 'G-E55L0N0HJX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvdwG5K7nOimHjoAvQ9Aqtmjc24dSu1M',
    appId: '1:941297246376:web:4cf85be0eb92951964629d',
    messagingSenderId: '941297246376',
    projectId: 'mini-app-9f9aa',
    authDomain: 'mini-app-9f9aa.firebaseapp.com',
    storageBucket: 'mini-app-9f9aa.firebasestorage.app',
    measurementId: 'G-E55L0N0HJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4l7JRRqxt2svNaITQPZ1k0EVrKQph9OQ',
    appId: '1:941297246376:android:4fd80b581acde04e64629d',
    messagingSenderId: '941297246376',
    projectId: 'mini-app-9f9aa',
    storageBucket: 'mini-app-9f9aa.firebasestorage.app',
  );

}